# Workflow to check Python code formatting

name: Python linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install black
        run: |
          pip install black[jupyter]
      - name: Check code style with Black
        run: |
          black --check .
